# Cloud Build configuration for training Docker image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/train.Dockerfile'
      - '-t'
      - '${_IMAGE_URI}'
      - '--platform'
      - 'linux/amd64'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_URI}'

images:
  - '${_IMAGE_URI}'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s  # 30 minutes

