# DVC pipeline parameters
# Referenced by dvc.yaml stage 5 (train)
# Modify these values and run `dvc repro` to retrain with new hyperparameters

train:
  batch_size: 32
  lr: 0.001
  num_epochs: 100

model:
  embedding_dim: 256
  hidden_dim: 256
  num_layers: 2
  num_heads: 2
  dropout: 0.1
