workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-8
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/base-cpu.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Building text-based I-I kNN graph (INTERACTED-ONLY)..."
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/graphs/build_ii_knn.py /tmp/build_ii_knn.py
          
          echo "[SETUP] Installing dependencies..."
          pip install -q numpy scipy scikit-learn google-cloud-storage
          
          echo "[SETUP] Running kNN construction (interacted-only)..."
          python3 /tmp/build_ii_knn.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --embeddings-path=gs://plotpointe-artifacts/embeddings/txt_interacted.npy \
            --output-prefix=gs://plotpointe-artifacts/graphs \
            --output-name=ii_edges_txt_interacted \
            --k=20 \
            --min-similarity=0.3 \
            --batch-size=1000
          
          echo "[SETUP] ✅ Text I-I kNN (interacted-only) complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

