workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-4
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/base-cpu.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Building interacted-only text embeddings subset..."
          echo "[SETUP] Uploading script to container..."
          gsutil cp gs://plotpointe-artifacts/code/scripts/build_interacted_text_subset.py /tmp/build_interacted_text_subset.py

          echo "[SETUP] Installing dependencies..."
          pip install -q numpy pandas pyarrow google-cloud-storage

          echo "[RUN] Running subset builder..."
          python3 /tmp/build_interacted_text_subset.py \
            --project-id=plotpointe \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --embeddings-uri=gs://plotpointe-artifacts/embeddings/txt.npy \
            --output-prefix=gs://plotpointe-artifacts/embeddings

          echo "[DONE] ✅ Interacted-only subset complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

