workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/base-cpu.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] U-I Edges v2 (Rating Weights)"
          echo "====================================="
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/graphs/build_ui_edges.py /tmp/build_ui_edges.py
          echo "[SETUP] Installing dependencies..."
          pip install -q numpy scipy pandas pyarrow google-cloud-storage
          echo "[SETUP] Running build_ui_edges.py (v2 with rating weights)..."
          python3 /tmp/build_ui_edges.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --output-prefix=gs://plotpointe-artifacts/graphs/v2
          echo "[SETUP] ✅ U-I edges v2 complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

