workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-8
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/base-cpu.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] I-I kNN Text v2 (Similarity Threshold)"
          echo "=============================================="
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/graphs/build_ii_knn.py /tmp/build_ii_knn.py
          
          echo "[SETUP] Installing dependencies..."
          pip install -q numpy scipy scikit-learn google-cloud-storage
          
          echo "[SETUP] Running kNN construction (v2 with threshold)..."
          python3 /tmp/build_ii_knn.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --embeddings-path=gs://plotpointe-artifacts/embeddings/v2/txt.npy \
            --output-prefix=gs://plotpointe-artifacts/graphs/v2 \
            --output-name=ii_edges_txt \
            --k=20 \
            --min-similarity=0.3 \
            --batch-size=1000
          
          echo "[SETUP] ✅ Text I-I kNN v2 complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

