workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/base-cpu.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Text Embeddings v2 (Enhanced Features)"
          echo "=============================================="
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/embed_text.py /tmp/embed_text.py
          echo "[SETUP] Installing dependencies..."
          pip install -q sentence-transformers pandas pyarrow google-cloud-aiplatform google-cloud-storage
          echo "[SETUP] Running embed_text.py (v2 with brand + categories)..."
          python3 /tmp/embed_text.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --output-prefix=gs://plotpointe-artifacts/embeddings/v2 \
            --experiment-name=recsys-dev \
            --model-name=all-MiniLM-L6-v2 \
            --batch-size=128
          echo "[SETUP] ✅ Text embeddings v2 complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

