workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/embed_image.py /tmp/embed_image.py
          echo "[SETUP] Installing dependencies..."
          pip install -q --upgrade pip
          pip uninstall -y transformers torch
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q 'transformers==4.35.2' pillow requests tqdm google-cloud-aiplatform google-cloud-storage
          echo "[SETUP] Running embed_image.py..."
          python3 /tmp/embed_image.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --output-prefix=gs://plotpointe-artifacts/embeddings \
            --experiment-name=recsys-dev \
            --model-name=openai/clip-vit-base-patch32 \
            --batch-size=32 \
            --max-items=150000 \
            --download-timeout=5
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com
# NO SPOT/PREEMPTIBLE - Use regular on-demand GPU for reliability

