workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-gpu.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Image Embeddings v2 (Normalized)"
          echo "========================================"
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/embed_image.py /tmp/embed_image.py
          echo "[SETUP] Installing dependencies..."
          pip install -q transformers pillow requests pandas pyarrow google-cloud-aiplatform google-cloud-storage
          echo "[SETUP] Running embed_image.py (v2 with normalization)..."
          python3 /tmp/embed_image.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --output-prefix=gs://plotpointe-artifacts/embeddings/v2 \
            --experiment-name=recsys-dev \
            --model-name=openai/clip-vit-base-patch32 \
            --batch-size=64
          echo "[SETUP] ✅ Image embeddings v2 complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

