workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-4
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: ghcr.io/axionis47/plotpointe-gat-recommendation:latest
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[RUN] Export item embeddings..."
          python3 tools/export_item_embeddings.py \
            --model-family=${MODEL_FAMILY:-gat_pyg} \
            --checkpoint=${CHECKPOINT_PT} \
            --project-id=${PROJECT_ID:-plotpointe} \
            --staging-prefix=${STAGING_PREFIX:-gs://plotpointe-artifacts/staging/amazon_electronics} \
            --graphs-prefix=${GRAPHS_PREFIX:-gs://plotpointe-artifacts/graphs} \
            --embeddings-prefix=${EMBEDDINGS_PREFIX:-gs://plotpointe-artifacts/embeddings} \
            --item-features=${ITEM_FEATURES:-fused} \
            --out-gcs=${OUT_GCS}
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

