workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/base-cpu.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/fuse_modal.py /tmp/fuse_modal.py
          echo "[SETUP] Installing dependencies..."
          pip install -q torch pandas pyarrow tqdm google-cloud-aiplatform google-cloud-storage
          echo "[SETUP] Running fuse_modal.py..."
          python3 /tmp/fuse_modal.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --embeddings-prefix=gs://plotpointe-artifacts/embeddings \
            --output-prefix=gs://plotpointe-artifacts/embeddings \
            --experiment-name=recsys-dev \
            --output-dim=128 \
            --hidden-dim=256 \
            --batch-size=512 \
            --epochs=5 \
            --lr=0.001
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

