workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-8
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Starting fusion (text+image) on L4 GPU..."
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/fuse_modal.py /tmp/fuse_modal.py
          echo "[SETUP] Installing dependencies..."
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q pandas pyarrow tqdm google-cloud-aiplatform google-cloud-storage
          echo "[WAIT] Waiting for text/image embeddings in GCS..."
          for i in {1..120}; do
            if gsutil -q stat gs://plotpointe-artifacts/embeddings/txt.npy && gsutil -q stat gs://plotpointe-artifacts/embeddings/img.npy; then
              echo "[WAIT] Found txt.npy and img.npy"
              break
            fi
            echo "[WAIT] Not ready yet... ($i/120) sleeping 30s"
            sleep 30
          done
          if ! gsutil -q stat gs://plotpointe-artifacts/embeddings/txt.npy || ! gsutil -q stat gs://plotpointe-artifacts/embeddings/img.npy; then
            echo "[ERROR] Required embeddings not found after waiting; exiting." >&2
            exit 1
          fi
          echo "[SETUP] Running fuse_modal.py..."
          python3 /tmp/fuse_modal.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --embeddings-prefix=gs://plotpointe-artifacts/embeddings \
            --output-prefix=gs://plotpointe-artifacts/embeddings \
            --experiment-name=recsys-dev \
            --output-dim=128 \
            --hidden-dim=256 \
            --batch-size=512 \
            --epochs=5 \
            --lr=0.001
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

