workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-gpu.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] Modal Fusion v2 (Contrastive Loss + Efficient Lookup)"
          echo "=============================================================="
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/fuse_modal.py /tmp/fuse_modal.py
          echo "[SETUP] Installing dependencies..."
          pip install -q torch pandas pyarrow numpy google-cloud-aiplatform google-cloud-storage tqdm
          echo "[SETUP] Running fuse_modal.py (v2 with improvements)..."
          python3 /tmp/fuse_modal.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --txt-embeddings-path=gs://plotpointe-artifacts/embeddings/v2/txt.npy \
            --img-embeddings-path=gs://plotpointe-artifacts/embeddings/v2/img.npy \
            --img-items-path=gs://plotpointe-artifacts/embeddings/v2/img_items.parquet \
            --txt-items-path=gs://plotpointe-artifacts/staging/amazon_electronics/items.parquet \
            --output-prefix=gs://plotpointe-artifacts/embeddings/v2 \
            --experiment-name=recsys-dev \
            --output-dim=128 \
            --hidden-dim=256 \
            --epochs=10 \
            --batch-size=512 \
            --lr=0.001
          echo "[SETUP] ✅ Modal fusion v2 complete!"
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

