workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SMOKE TEST] Downloading test script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/embeddings/smoke_test_gpu.py /tmp/smoke_test_gpu.py
          echo "[SMOKE TEST] Installing dependencies..."
          pip install -q --upgrade pip
          pip uninstall -y transformers torch
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q 'transformers==4.35.2' pillow requests
          echo "[SMOKE TEST] Running GPU smoke test..."
          python3 /tmp/smoke_test_gpu.py
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com
scheduling:
  strategy: SPOT
  restartJobOnWorkerRestart: false

