workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-8
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] LightGCN training on L4 (us-central1, d=128)..."
          gsutil cp gs://plotpointe-artifacts/code/train/train_lightgcn.py /tmp/train_lightgcn.py
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q pandas pyarrow numpy google-cloud-aiplatform google-cloud-storage
          python3 /tmp/train_lightgcn.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --graphs-prefix=gs://plotpointe-artifacts/graphs \
            --models-prefix=gs://plotpointe-artifacts/models/lightgcn \
            --embed-dim=128 \
            --layers=3 \
            --lr=0.001 \
            --l2=0.0001 \
            --epochs=50 \
            --batch-size=8192 \
            --neg-per-pos=5 \
            --seed=42 \
            --eval-neg-k=1000
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

