workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-4
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] GAT (PyG) training on L4..."
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/train/train_gat_pyg.py /tmp/train_gat_pyg.py

          echo "[SETUP] Installing dependencies..."
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q pandas pyarrow numpy google-cloud-aiplatform google-cloud-storage
          # PyG wheels matching torch==2.1.0+cu121
          pip install -q pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric \
            -f https://data.pyg.org/whl/torch-2.1.0+cu121.html

          echo "[RUN] Starting training (PyG GAT)..."
          python3 /tmp/train_gat_pyg.py \
            --project-id=${PROJECT_ID:-plotpointe} \
            --region=${REGION:-us-central1} \
            --staging-prefix=${STAGING_PREFIX:-gs://plotpointe-artifacts/staging/amazon_electronics} \
            --graphs-prefix=${GRAPHS_PREFIX:-gs://plotpointe-artifacts/graphs} \
            --embeddings-prefix=${EMBEDDINGS_PREFIX:-gs://plotpointe-artifacts/embeddings} \
            --models-prefix=${MODELS_PREFIX:-gs://plotpointe-artifacts/models/gat/pyg} \
            --hidden-dim=${HIDDEN_DIM:-128} \
            --layers=${LAYERS:-2} \
            --heads=${HEADS:-1} \
            --epochs=${EPOCHS:-20} \
            --samples-per-epoch=${SAMPLES_PER_EPOCH:-200000} \
            --seed=${SEED:-42} \
            --eval-neg-k=${EVAL_NEG_K:-1000} \
            --item-features=${ITEM_FEATURES:-fused} \
            --loss=${LOSS:-bpr}
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

