workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-4
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: ghcr.io/axionis47/gat-recsys:latest
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[RUN] Training (Custom GAT) with prebuilt image..."
          python3 -m scripts.train_gat_custom \
            --project-id=${PROJECT_ID:-plotpointe} \
            --region=${REGION:-us-central1} \
            --staging-prefix=${STAGING_PREFIX:-gs://plotpointe-artifacts/staging/amazon_electronics} \
            --graphs-prefix=${GRAPHS_PREFIX:-gs://plotpointe-artifacts/graphs} \
            --embeddings-prefix=${EMBEDDINGS_PREFIX:-gs://plotpointe-artifacts/embeddings} \
            --models-prefix=${MODELS_PREFIX:-gs://plotpointe-artifacts/models/gat/custom} \
            --hidden-dim=${HIDDEN_DIM:-128} \
            --layers=${LAYERS:-2} \
            --epochs=${EPOCHS:-20} \
            --samples-per-epoch=${SAMPLES_PER_EPOCH:-200000} \
            --seed=${SEED:-42} \
            --eval-neg-k=${EVAL_NEG_K:-1000} \
            --item-features=${ITEM_FEATURES:-fused} \
            --loss=${LOSS:-bpr} ${USE_VERTEX_EXP:+--use-vertex-exp} ${EXP_NAME:+--exp-name=${EXP_NAME}} ${RUN_NAME:+--run-name=${RUN_NAME}}
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

