workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-4
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] GAT (custom, loss=BCE) training on L4..."
          gsutil cp gs://plotpointe-artifacts/code/train/train_gat_custom.py /tmp/train_gat_custom.py
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q pandas pyarrow numpy google-cloud-aiplatform google-cloud-storage
          python3 /tmp/train_gat_custom.py \
            --project-id=plotpointe \
            --region=us-central1 \
            --staging-prefix=gs://plotpointe-artifacts/staging/amazon_electronics \
            --graphs-prefix=gs://plotpointe-artifacts/graphs \
            --embeddings-prefix=gs://plotpointe-artifacts/embeddings \
            --models-prefix=gs://plotpointe-artifacts/models/gat/custom \
            --hidden-dim=128 \
            --layers=2 \
            --epochs=20 \
            --samples-per-epoch=200000 \
            --seed=42 \
            --eval-neg-k=1000 \
            --item-features=fused \
            --loss=bce
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com

