workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-4
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/pytorch-cu121.2-1.py310
      command:
        - /bin/bash
        - -lc
        - |
          set -e
          echo "[SETUP] LightGCN training on L4..."
          echo "[SETUP] Downloading script from GCS..."
          gsutil cp gs://plotpointe-artifacts/code/train/train_lightgcn.py /tmp/train_lightgcn.py

          echo "[SETUP] Installing dependencies..."
          pip install -q torch==2.1.0 torchvision==0.16.0
          pip install -q pandas pyarrow numpy google-cloud-aiplatform google-cloud-storage

          echo "[RUN] Starting training..."
          python3 /tmp/train_lightgcn.py \
            --project-id=${PROJECT_ID:-plotpointe} \
            --region=${REGION:-us-central1} \
            --staging-prefix=${STAGING_PREFIX:-gs://plotpointe-artifacts/staging/amazon_electronics} \
            --graphs-prefix=${GRAPHS_PREFIX:-gs://plotpointe-artifacts/graphs} \
            --models-prefix=${MODELS_PREFIX:-gs://plotpointe-artifacts/models/lightgcn} \
            --embed-dim=${EMBED_DIM:-64} \
            --layers=${LAYERS:-3} \
            --lr=${LR:-0.001} \
            --l2=${L2:-0.0001} \
            --epochs=${EPOCHS:-50} \
            --batch-size=${BATCH_SIZE:-8192} \
            --neg-per-pos=${NEG_PER_POS:-5} \
            --seed=${SEED:-42} \
            --eval-neg-k=${EVAL_NEG_K:-1000}
serviceAccount: sa-pipeline@plotpointe.iam.gserviceaccount.com
