name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install project and dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          # Minimal runtime deps needed by tests
          pip install "numpy>=1.24,<2.0" "torch==2.1.0"
          # Install project and dev tooling
          pip install .
          pip install black isort flake8 mypy pytest pytest-cov pytest-timeout pylint

      - name: Lint (black/isort/flake8)
        continue-on-error: true
        run: |
          black --check .
          isort --check-only .
          flake8 . --max-line-length=100 --exclude=.venv,.git,__pycache__

      - name: Type check (mypy)
        continue-on-error: true
        run: |
          mypy .

      - name: Tests (unit only)
        run: |
          pytest -q --cov-fail-under=0

      - name: CLI smoke (embeddings)
        run: |
          python -m plotpointe.embeddings.cli --help

