name: Terraform Validate (IaC)

on:
  push:
    paths:
      - 'terraform/**.tf'
      - '.github/workflows/terraform.yml'
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'terraform/**.tf'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

